import type { DeepKeys, DeepValue, FieldApi, ReactFormExtendedApi, StandardSchemaV1 } from '@tanstack/react-form';


export function asSchemaField<
    TParentData,
    TName extends DeepKeys<TParentData>,
    TData extends DeepValue<TParentData, TName>,
    TOnMount extends StandardSchemaV1<TData, unknown> | undefined,
    TOnChange extends StandardSchemaV1<TData, unknown> | undefined,
    TOnChangeAsync extends StandardSchemaV1<TData, unknown> | undefined,
    TOnBlur extends StandardSchemaV1<TData, unknown> | undefined,
    TOnBlurAsync extends StandardSchemaV1<TData, unknown> | undefined,
    TOnSubmit extends StandardSchemaV1<TData, unknown> | undefined,
    TOnSubmitAsync extends StandardSchemaV1<TData, unknown> | undefined,
    TOnDynamic extends StandardSchemaV1<TData, unknown> | undefined,
    TOnDynamicAsync extends StandardSchemaV1<TData, unknown> | undefined,
    TFormOnMount extends StandardSchemaV1<TParentData, unknown> | undefined,
    TFormOnChange extends StandardSchemaV1<TParentData, unknown> | undefined,
    TFormOnChangeAsync extends StandardSchemaV1<TParentData, unknown> | undefined,
    TFormOnBlur extends StandardSchemaV1<TParentData, unknown> | undefined,
    TFormOnBlurAsync extends StandardSchemaV1<TParentData, unknown> | undefined,
    TFormOnSubmit extends StandardSchemaV1<TParentData, unknown> | undefined,
    TFormOnSubmitAsync extends StandardSchemaV1<TParentData, unknown> | undefined,
    TFormOnDynamic extends StandardSchemaV1<TParentData, unknown> | undefined,
    TFormOnDynamicAsync extends StandardSchemaV1<TParentData, unknown> | undefined,
    TFormOnServer extends StandardSchemaV1<TParentData, unknown> | undefined,
    TParentSubmitMeta,
>(
    field: FieldApi<
        TParentData,
        TName,
        TData,
        TOnMount,
        TOnChange,
        TOnChangeAsync,
        TOnBlur,
        TOnBlurAsync,
        TOnSubmit,
        TOnSubmitAsync,
        TOnDynamic,
        TOnDynamicAsync,
        TFormOnMount,
        TFormOnChange,
        TFormOnChangeAsync,
        TFormOnBlur,
        TFormOnBlurAsync,
        TFormOnSubmit,
        TFormOnSubmitAsync,
        TFormOnDynamic,
        TFormOnDynamicAsync,
        TFormOnServer,
        TParentSubmitMeta
    >,
): FieldApi<
    TParentData,
    TName,
    TData,
    StandardSchemaV1<TData, unknown> | undefined,
    StandardSchemaV1<TData, unknown> | undefined,
    StandardSchemaV1<TData, unknown> | undefined,
    StandardSchemaV1<TData, unknown> | undefined,
    StandardSchemaV1<TData, unknown> | undefined,
    StandardSchemaV1<TData, unknown> | undefined,
    StandardSchemaV1<TData, unknown> | undefined,
    StandardSchemaV1<TData, unknown> | undefined,
    StandardSchemaV1<TData, unknown> | undefined,
    StandardSchemaV1<TParentData, unknown> | undefined,
    StandardSchemaV1<TParentData, unknown> | undefined,
    StandardSchemaV1<TParentData, unknown> | undefined,
    StandardSchemaV1<TParentData, unknown> | undefined,
    StandardSchemaV1<TParentData, unknown> | undefined,
    StandardSchemaV1<TParentData, unknown> | undefined,
    StandardSchemaV1<TParentData, unknown> | undefined,
    StandardSchemaV1<TParentData, unknown> | undefined,
    StandardSchemaV1<TParentData, unknown> | undefined,
    StandardSchemaV1<TParentData, unknown> | undefined,
    TParentSubmitMeta
> {
    return field as any;
}

export function asSchemaForm<
    TFormData,
    TOnMount extends StandardSchemaV1<TFormData, unknown> | undefined,
    TOnChange extends StandardSchemaV1<TFormData, unknown> | undefined,
    TOnChangeAsync extends StandardSchemaV1<TFormData, unknown> | undefined,
    TOnBlur extends StandardSchemaV1<TFormData, unknown> | undefined,
    TOnBlurAsync extends StandardSchemaV1<TFormData, unknown> | undefined,
    TOnSubmit extends StandardSchemaV1<TFormData, unknown> | undefined,
    TOnSubmitAsync extends StandardSchemaV1<TFormData, unknown> | undefined,
    TOnDynamic extends StandardSchemaV1<TFormData, unknown> | undefined,
    TOnDynamicAsync extends StandardSchemaV1<TFormData, unknown> | undefined,
    TOnServer extends StandardSchemaV1<TFormData, unknown> | undefined,
    TSubmitMeta,
>(
    form: ReactFormExtendedApi<
        TFormData,
        TOnMount,
        TOnChange,
        TOnChangeAsync,
        TOnBlur,
        TOnBlurAsync,
        TOnSubmit,
        TOnSubmitAsync,
        TOnDynamic,
        TOnDynamicAsync,
        TOnServer,
        TSubmitMeta
    >,
): ReactFormExtendedApi<
    TFormData,
    StandardSchemaV1<TFormData, unknown> | undefined,
    StandardSchemaV1<TFormData, unknown> | undefined,
    StandardSchemaV1<TFormData, unknown> | undefined,
    StandardSchemaV1<TFormData, unknown> | undefined,
    StandardSchemaV1<TFormData, unknown> | undefined,
    StandardSchemaV1<TFormData, unknown> | undefined,
    StandardSchemaV1<TFormData, unknown> | undefined,
    StandardSchemaV1<TFormData, unknown> | undefined,
    StandardSchemaV1<TFormData, unknown> | undefined,
    StandardSchemaV1<TFormData, unknown> | undefined,
    TSubmitMeta
> {
    return form as any;
}
