import type { OmitFrom } from '@/types/from';


export interface Language {
    code: Intl.UnicodeBCP47LocaleIdentifier;
    name: string;
    flag: string;
}

export const defaultLanguages = {
    'af-ZA': { name: 'Afrikaans', flag: '🇿🇦' },
    'sq-AL': { name: 'Shqip', flag: '🇦🇱' },
    'am-ET': { name: 'አማርኛ', flag: '🇪🇹' },
    'ar-SA': { name: 'العربية (السعودية)', flag: '🇸🇦' },
    'ar-EG': { name: 'العربية (مصر)', flag: '🇪🇬' },
    'hy-AM': { name: 'Հայերեն', flag: '🇦🇲' },
    'az-AZ': { name: 'Azərbaycanca', flag: '🇦🇿' },
    'eu-ES': { name: 'Euskara', flag: '🇪🇸' },
    'be-BY': { name: 'Беларуская', flag: '🇧🇾' },
    'bn-BD': { name: 'বাংলা', flag: '🇧🇩' },
    'bs-BA': { name: 'Bosanski', flag: '🇧🇦' },
    'bg-BG': { name: 'Български', flag: '🇧🇬' },
    'ca-ES': { name: 'Català', flag: '🇪🇸' },
    'zh-CN': { name: '中文 (简体)', flag: '🇨🇳' },
    'zh-TW': { name: '中文 (繁體)', flag: '🇹🇼' },
    'hr-HR': { name: 'Hrvatski', flag: '🇭🇷' },
    'cs-CZ': { name: 'Čeština', flag: '🇨🇿' },
    'da-DK': { name: 'Dansk', flag: '🇩🇰' },
    'nl-NL': { name: 'Nederlands', flag: '🇳🇱' },
    'en-US': { name: 'English (US)', flag: '🇺🇸' },
    'en-GB': { name: 'English (UK)', flag: '🇬🇧' },
    'et-EE': { name: 'Eesti', flag: '🇪🇪' },
    'fi-FI': { name: 'Suomi', flag: '🇫🇮' },
    'fr-FR': { name: 'Français (France)', flag: '🇫🇷' },
    'fr-CA': { name: 'Français (Canada)', flag: '🇨🇦' },
    'gl-ES': { name: 'Galego', flag: '🇪🇸' },
    'ka-GE': { name: 'ქართული', flag: '🇬🇪' },
    'de-DE': { name: 'Deutsch (Deutschland)', flag: '🇩🇪' },
    'de-AT': { name: 'Deutsch (Österreich)', flag: '🇦🇹' },
    'de-CH': { name: 'Deutsch (Schweiz)', flag: '🇨🇭' },
    'el-GR': { name: 'Ελληνικά', flag: '🇬🇷' },
    'gu-IN': { name: 'ગુજરાતી', flag: '🇮🇳' },
    'he-IL': { name: 'עברית', flag: '🇮🇱' },
    'hi-IN': { name: 'हिन्दी', flag: '🇮🇳' },
    'hu-HU': { name: 'Magyar', flag: '🇭🇺' },
    'is-IS': { name: 'Íslenska', flag: '🇮🇸' },
    'id-ID': { name: 'Bahasa Indonesia', flag: '🇮🇩' },
    'ga-IE': { name: 'Gaeilge', flag: '🇮🇪' },
    'it-IT': { name: 'Italiano', flag: '🇮🇹' },
    'it-CH': { name: 'Italiano (Svizzera)', flag: '🇨🇭' },
    'ja-JP': { name: '日本語', flag: '🇯🇵' },
    'kn-IN': { name: 'ಕನ್ನಡ', flag: '🇮🇳' },
    'ko-KR': { name: '한국어', flag: '🇰🇷' },
    'lv-LV': { name: 'Latviešu', flag: '🇱🇻' },
    'lt-LT': { name: 'Lietuvių', flag: '🇱🇹' },
    'mk-MK': { name: 'Македонски', flag: '🇲🇰' },
    'ms-MY': { name: 'Bahasa Melayu', flag: '🇲🇾' },
    'mt-MT': { name: 'Malti', flag: '🇲🇹' },
    'no-NO': { name: 'Norsk (Bokmål)', flag: '🇳🇴' },
    'pl-PL': { name: 'Polski', flag: '🇵🇱' },
    'pt-PT': { name: 'Português (Portugal)', flag: '🇵🇹' },
    'pt-BR': { name: 'Português (Brasil)', flag: '🇧🇷' },
    'ro-RO': { name: 'Română', flag: '🇷🇴' },
    'ru-RU': { name: 'Русский', flag: '🇷🇺' },
    'sr-RS': { name: 'Српски', flag: '🇷🇸' },
    'sk-SK': { name: 'Slovenčina', flag: '🇸🇰' },
    'sl-SI': { name: 'Slovenščina', flag: '🇸🇮' },
    'es-ES': { name: 'Español (España)', flag: '🇪🇸' },
    'es-MX': { name: 'Español (México)', flag: '🇲🇽' },
    'sw-KE': { name: 'Kiswahili', flag: '🇰🇪' },
    'sv-SE': { name: 'Svenska', flag: '🇸🇪' },
    'ta-IN': { name: 'தமிழ்', flag: '🇮🇳' },
    'te-IN': { name: 'తెలుగు', flag: '🇮🇳' },
    'th-TH': { name: 'ไทย', flag: '🇹🇭' },
    'tr-TR': { name: 'Türkçe', flag: '🇹🇷' },
    'uk-UA': { name: 'Українська', flag: '🇺🇦' },
    'ur-PK': { name: 'اردو', flag: '🇵🇰' },
    'vi-VN': { name: 'Tiếng Việt', flag: '🇻🇳' },
    'zu-ZA': { name: 'isiZulu', flag: '🇿🇦' },
} as const satisfies Record<string, OmitFrom<Language, 'code'>>;


export type DefaultLanguageCode = keyof typeof defaultLanguages;
export type LanguageCode = DefaultLanguageCode | (Intl.UnicodeBCP47LocaleIdentifier & {});
